export const RABBITMQ_LOGGER_WRAPPER = 'RABBITMQ_LOGGER_WRAPPER';

export const RABBITMQ_SENDER_OPTIONS = 'RABBITMQ_SENDER_OPTIONS';
export const RABBITMQ_CONSUMER_OPTIONS = 'RABBITMQ_CONSUMER_OPTIONS';
